### ISSUE TITLE
[13] Failed Scanning case

### ISSUE THREAD

**Issue by android-app-sast** [alterakey/trueseeing#290] opened 2023-11-23 03:27 UTC
Hi！
I got a mistake when scanning an application
Strangely, I succeeded in scanning a certain application, and failed in trying more than 10 other APKs. These APKs have not been confused.
The following is the specific error information
```
$ docker run --rm -v $(pwd):/out  alterakey/trueseeing  goatdroid.apk
analyze: disassembling... done.
analyze: 18193 ops, 570 classes, methods...                    Traceback (most recent call last):
  File "/usr/local/bin/trueseeing", line 8, in <module>
    sys.exit(invoke())
             ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/trueseeing/app/_dummy.py", line 31, in invoke
    trueseeing.app.shell.Shell().invoke()
  File "/usr/local/lib/python3.11/site-packages/trueseeing/app/shell.py", line 255, in invoke
    return self._launch(ScanMode(files).invoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/trueseeing/app/shell.py", line 148, in _launch
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/trueseeing/app/scan.py", line 53, in invoke
    if await session.invoke(f):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/trueseeing/app/scan.py", line 82, in invoke
    await context.analyze()
  File "/usr/local/lib/python3.11/site-packages/trueseeing/core/context.py", line 85, in analyze
    SmaliAnalyzer(self.store()).analyze()
  File "/usr/local/lib/python3.11/site-packages/trueseeing/core/code/parse.py", line 94, in analyze
    analyzed_methods = self._store.op_generate_methodmap(c=c)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/trueseeing/core/store.py", line 93, in op_generate_methodmap
    c.execute('insert into ops_method(method,op) select tmp1.op,ops.op from tmp1 join tmp2 on (tmp1.rowid=tmp2.rowid) left join ops on (ops.op between tmp1.op and tmp2.op)')
sqlite3.IntegrityError: UNIQUE constraint failed: ops_method.op


```

**Comment by alterakey** [comment] 2023-11-23 11:43
Hello @android-app-sast , I appriciate your report.
I will investigate the issue.
Would you mind if I ask you to provide some of failed APK? (a few sould suffice, I guess)

Thanks in advance.

**Comment by alterakey** [comment] 2023-11-23 11:48
And could you try building the container from the current HEAD and scanning with inspect mode (i.e. docker run ... trueseeing --inspect target.apk -> `as` -> `gh report.html`)?
Since many fixes done since the last release.
Thanks.

**Comment by alterakey** [comment] 2023-11-23 11:55
Confirmed; looking into the issue.
```
florence:trueseeing alterakey$ docker run -it --rm -v $(pwd):/out trueseeing --inspect goatdroid.apk 
[+] Trueseeing 2.1.8.1 [inspect mode]
ts[goatdroid.apk]> aa
[*] analyzing goatdroid.apk
[*] analyze: disassembling... done.
[*] analyze: 18193 ops, 570 classes, methods...                    [-] fatal: unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/trueseeing/app/inspect.py", line 227, in run
    await ent(tokens)
  File "/usr/local/lib/python3.12/site-packages/trueseeing/app/inspect.py", line 325, in _analyze2
    await self._analyze(args)
  File "/usr/local/lib/python3.12/site-packages/trueseeing/app/inspect.py", line 320, in _analyze
    await context.analyze()
  File "/usr/local/lib/python3.12/site-packages/trueseeing/core/context.py", line 85, in analyze
    SmaliAnalyzer(self.store()).analyze()
  File "/usr/local/lib/python3.12/site-packages/trueseeing/core/code/parse.py", line 94, in analyze
    analyzed_methods = self._store.op_generate_methodmap(c=c)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/trueseeing/core/store.py", line 93, in op_generate_methodmap
    c.execute('insert into ops_method(method,op) select tmp1.op,ops.op from tmp1 join tmp2 on (tmp1.rowid=tmp2.rowid) left join ops on (ops.op between tmp1.op and tmp2.op)')
sqlite3.IntegrityError: UNIQUE constraint failed: ops_method.op
```

**Comment by alterakey** [comment] 2023-11-23 12:26
Method boundaries are not detected?
```
sqlite> select * from tmp_method where method=41009;
method|op
41009|41009
41009|41010
41009|41011
41009|41012
41009|41013
41009|41014
41009|41015
41009|41016
41009|41017
...
```

```
sqlite> select * from ops where op between 41009 and 41016;
op|idx|t|v
41009|0|directive|method
41010|1|id|public
41011|2|id|abstract
41012|3|id|initialize
41013|4|reflike|(Lcom/actionbarsherlock/internal/view/menu/MenuItemImpl;I)V
41014|0|directive|end
41015|1|id|method
41016|0|directive|method
```

**Comment by alterakey** [comment] 2023-11-23 13:11
Additionally: lexer failing on ActionBarSherlock?
```
sqlite> select * from ops where op between 55673 and 55739;
op|idx|t|v
55673|0|directive|method
55674|1|id|public
55675|2|id|on
55676|3|reflike|Click(Landroid/view/View;)V
55677|0|directive|locals
55678|1|reflike|5
55679|0|directive|class
55680|1|id|public
55681|2|id|final
55682|3|reflike|Lcom/actionbarsherlock/widget/ActivityChooserModel$ActivityResolveInfo;
55683|0|directive|super
55684|1|reflike|Ljava/lang/Object;
55685|0|directive|source
55686|1|string|ActivityChooserModel.java
```

```
smali/classes/com/actionbarsherlock/widget/ActivityChooserModel$ActivityResolveInfo.smali|.class public final Lcom/actionbarsherlock/widget/ActivityChooserModel$ActivityResolveInfo;
.super Ljava/lang/Object;
.source "ActivityChooserModel.java"

# interfaces
.implements Ljava/lang/Comparable;
...
```

**Comment by alterakey** [comment] 2023-11-23 14:07
Looks like a lexer failure.
```
[*] analyze: disassembling... done.
[.] op: <Op[None] t=directive v=class, p=[<Op[None] t=reflike v=Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;, p=[]>]>
[.] op: <Op[None] t=directive v=super, p=[<Op[None] t=reflike v=Ljava/lang/Object;, p=[]>]>
[.] op: <Op[None] t=directive v=source, p=[<Op[None] t=string v=AccessibilityServiceInfoCompatIcs.java, p=[]>]>
[.] op: <Op[None] t=comment v= direct methods, p=[]>
[.] op: <Op[None] t=directive v=method, p=[<Op[None] t=id v=constructor, p=[]>, <Op[None] t=reflike v=<init>()V, p=[]>]>
[.] op: <Op[None] t=directive v=locals, p=[<Op[None] t=reflike v=0, p=[]>]>
[.] op: <Op[None] t=directive v=prologue, p=[]>
[.] op: <Op[None] t=directive v=line, p=[<Op[None] t=reflike v=26, p=[]>]>
[.] op: <Op[None] t=id v=invoke-direct, p=[<Op[None] t=multireg v=p0, p=[]>, <Op[None] t=reflike v=Ljava/lang/Object;-><init>()V, p=[]>]>
[.] op: <Op[None] t=id v=return-void, p=[]>
[.] op: <Op[None] t=directive v=end, p=[<Op[None] t=id v=method, p=[]>]>
[.] op: <Op[None] t=directive v=method, p=[<Op[None] t=id v=public, p=[]>, <Op[None] t=id v=static, p=[]>, <Op[None] t=id v=get, p=[]>, <Op[None] t=reflike v=CanRetrieveWindowContent(Landroid/accessibilityservice/AccessibilityServiceInfo;)Z, p=[]>]>
[.] op: <Op[None] t=directive v=locals, p=[<Op[None] t=reflike v=1, p=[]>]>
[.] op: <Param param:param:[<Op[None] t=reg v=p0, p=[]>, <Op[None] t=string v=info, p=[]>, <Op[None] t=comment v= Landroid/accessibilityservice/AccessibilityServiceInfo;, p=[]>], content:['    .prologue', '    .line 29', '    invoke-virtual {p0}, Landroid/accessibilityservice/AccessibilityServiceInfo;->getCanRetrieveWindowContent()Z', '    move-result v0', '    return v0', '.end method', '.method public static getDescription(Landroid/accessibilityservice/AccessibilityServiceInfo;)Ljava/lang/String;', '    .locals 1', '    .param p0, "info"    # Landroid/accessibilityservice/AccessibilityServiceInfo;', '    .prologue', '    .line 33', '    invoke-virtual {p0}, Landroid/accessibilityservice/AccessibilityServiceInfo;->getDescription()Ljava/lang/String;', '    move-result-object v0', '    return-object v0', '.end method', '.method public static getId(Landroid/accessibilityservice/AccessibilityServiceInfo;)Ljava/lang/String;', '    .locals 1', '    .param p0, "info"    # Landroid/accessibilityservice/AccessibilityServiceInfo;', '    .prologue', '    .line 37', '    invoke-virtual {p0}, Landroid/accessibilityservice/AccessibilityServiceInfo;->getId()Ljava/lang/String;', '    move-result-object v0', '    return-object v0', '.end method', '.method public static getResolveInfo(Landroid/accessibilityservice/AccessibilityServiceInfo;)Landroid/content/pm/ResolveInfo;', '    .locals 1', '    .param p0, "info"    # Landroid/accessibilityservice/AccessibilityServiceInfo;', '    .prologue', '    .line 41', '    invoke-virtual {p0}, Landroid/accessibilityservice/AccessibilityServiceInfo;->getResolveInfo()Landroid/content/pm/ResolveInfo;', '    move-result-object v0', '    return-object v0', '.end method', '.method public static getSettingsActivityName(Landroid/accessibilityservice/AccessibilityServiceInfo;)Ljava/lang/String;', '    .locals 1', '    .param p0, "info"    # Landroid/accessibilityservice/AccessibilityServiceInfo;', '    .prologue', '    .line 45', '    invoke-virtual {p0}, Landroid/accessibilityservice/AccessibilityServiceInfo;->getSettingsActivityName()Ljava/lang/String;', '    move-result-object v0', '    return-object v0', '.end method', '']>
[.] op: <Op[None] t=directive v=class, p=[<Op[None] t=id v=interface, p=[]>, <Op[None] t=id v=abstract, p=[]>, <Op[None] t=reflike v=Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;, p=[]>]>
```

**Comment by android-app-sast** [comment] 2023-11-23 14:17
Hi! Thanks for your reply, I just sent an email with failed scan apk attachment to you, but it was returned, may provide an alternative channel? I will send you a new one. Thanks again for your effort to the question

**Comment by alterakey** [comment] 2023-11-23 14:18
Thanks for your quick response, and I feel sorry for taking your time.
Could you encrypt it with 7zip or gpg  or something like that and send to alterakey@protonmail.com ?
Thanks again.

**Comment by alterakey** [comment] 2023-11-23 15:08
@android-app-sast , I have merged experimental fixes for method mapping logic and failed lexer.
Could you check if the fixes works for you? Thanks.

(I have checked against goatdroid and it seems to work)

**Comment by android-app-sast** [comment] 2023-11-23 17:26
@alterakey  Thanks so much for your fix, and i'm so sorry for that i don't know how to build. As when i run the python file _dummy.py, it also reported the error:
```
Traceback (most recent call last):
  File "_dummy.py", line 34, in &lt;module&gt;
    invoke() 
  File "_dummy.py", line 30, in invoke
    import trueseeing.app.shell
  File "/home/dell/.local/lib/python3.8/site-packages/trueseeing/app/shell.py", line 20, in &lt;module&gt;
    import asyncio
  File "/usr/lib/python3.8/asyncio/__init__.py", line 8, in &lt;module&gt;
    from .base_events import *
  File "/usr/lib/python3.8/asyncio/base_events.py", line 39, in &lt;module&gt;
    from . import coroutines
  File "/usr/lib/python3.8/asyncio/coroutines.py", line 5, in &lt;module&gt;
    import inspect
  File "/home/dell/zjy/32新增工具/trueseeing-master/trueseeing/app/inspect.py", line 27, in &lt;module&gt;
    from trueseeing.core.ui import ui
  File "/home/dell/.local/lib/python3.8/site-packages/trueseeing/core/ui.py", line 21, in &lt;module&gt;
    from functools import cache
ImportError: cannot import name 'cache' from 'functools' (/usr/lib/python3.8/functools.py)
```
Perhaps I built this wrong. If possible, providing a tutorial would be even better. Thanks again and so sorry for taking your time.

**Comment by alterakey** [comment] 2023-11-24 00:27
@android-app-sast, sorry for the confusion (NB. for the error, _dummy is the CLI entrypoint and trueseeing requires Python 3.9 or later; currently I am using 3.11 for the containers)

Surely I will provide build instruction in README.
For the time being, please do following to build trueseeing from git:
```
$ git clone https://github.com/alterakey/trueseeing.git wc
$ cd wc
$ python3 -m venv .venv
$ source .venv/bin/activate
(.venv) $ pip install -U pip flit
(.venv) $ (flit build && docker build -t trueseeing --build-arg dist=dist/trueseeing*.whl .)
```

Thanks again.

**Comment by android-app-sast** [comment] 2023-11-24 03:47
Hi！ @alterakey  So thanks for your fix. I have scanned successfully. Thanks again for your patience and effort!

**Comment by alterakey** [comment] 2023-11-24 04:28
@android-app-sast, thank you for the testing! Closing the issue.

**Closed by alterakey** 2023-11-24 04:28 UTC
Labels: bug
